" Vundle
set nocompatible
filetype off
" https://github.com/VundleVim/Vundle.vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Require plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'chr4/nginx.vim'
Plugin 'junegunn/goyo.vim'
" All plugins above
call vundle#end()            " required
filetype plugin indent on    " required

" \ global search thanks to `ag`
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" bind \ (backward slash) to grep shortcut
command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
nnoremap ` :Ag<SPACE>

" general
set number                     " Show current line number
set relativenumber             " Show relative line numbers
syntax on
filetype plugin indent on

set tabstop=4
set shiftwidth=2
set expandtab

" Easier buffer navigation, \b
nnoremap <Leader>b :ls<CR>:b<Space>
nnoremap <Leader>e :b<Space>#<CR>

nnoremap S "_diwP


" trim spaces on save
autocmd BufWritePre <buffer> %s/\s\+$//e
" restrict above with adding FileType java,cpp,php just after autocmd

" Make backspace work normally
set backspace=indent,eol,start
let g:ctrlp_reuse_window = 'netrw\|help\|quickfix'
