export PATH=$HOME/bin:$HOME/.cargo/bin:/usr/local/bin:$HOME/.local/bin:$PATH
export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="robbyrussell"

DISABLE_AUTO_UPDATE="false"
# export UPDATE_ZSH_DAYS=13

# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(
  git
  docker
  z
)

source $ZSH/oh-my-zsh.sh

export SSH_KEY_PATH="~/.ssh/rsa_id"

# Aliases
alias v="vim"

alias dl='docker logs'
alias dps='docker ps'
alias drm='docker rm'
alias ds='docker stop -t 0'

export VISUAL=vim
export EDITOR="$VISUAL"

# Added outside of dotfiles.
#
alias docker='sudo docker'
alias tmux='tmux attach || tmux'
